### ISSUE TITLE
希望增加以下输入框的焦点（回车）

### ISSUE THREAD

**Issue by Matzoh** [anrgct/utools-saladict#11]
1. 给沙拉查词绑定utools全局快捷键
2. 使用快捷键直接呼出沙拉查词
3. 输入单词后，按回车键没有反应，需要用鼠标手动点击输入框后才可以正常查询

**Comment by anrgct** [comment]
1.2 在设置—全局快捷键，给功能关键字“沙拉查词”设置一个快捷键就可以全局呼出，如果是要自动查询选中的文本，只能用utools的超级面板，在任意软件选中文本后呼出超级面板，然后选择查拉查词就可以自动查词；
3 我本机沙拉查词界面的的输入框回车后可以触发查询的，你可以试试到utools插件中心——账号与数据——沙拉查词——文档——清空，重启utools，再打开沙拉查词

**Comment by Matzoh** [comment]
不好意思，是我没说清楚，1/2/3是这个问题的复现流程
问题：快捷键呼出后，输入单词查询，按回车不能自动查询

下面是复现的动图，有键盘操作记录

![2021_01_21_2021-01-21-15.56.19](https://cdn.jsdelivr.net/gh/matzoh/wzx@master/uPic/2021/01/2021_01_21_2021-01-21-15.56.19.gif)
