### ISSUE TITLE
有道 谷歌 CNKI翻译显示不出来

### ISSUE THREAD

**Issue by youngerruan** [anrgct/utools-saladict#15]
经过多次测试，有道 谷歌 CNKI翻译均显示不出来，未加自定义API。
![Snipaste_2021-03-31_20-17-24](https://user-images.githubusercontent.com/21980789/113143367-a5224600-925e-11eb-89e4-b61f829953f0.png)

**Comment by youngerruan** [comment]
刚刚发现另外一款讯飞OCR插件也是作者做出来的！太厉害了，喜欢合并换行功能！刚好可以和这个插件联动！

**Comment by anrgct** [comment]
谷歌我本地可以的，应该是网络问题。有道 、 CNKI本地也不行，后面再修复

**Comment by cool-delete** [comment]
我修复了之后 有道可以CNKI不行

**Comment by youngerruan** [comment]
> 谷歌我本地可以的，应该是网络问题。有道 、 CNKI本地也不行，后面再修复

好的，谢谢作者回复。

**Comment by anrgct** [comment]
v0.2.10 已修复有道翻译，CNKI时好时坏不清楚原因，暂时这样
