### ISSUE TITLE
这么好的插件，作者是已经从uTools里下架了吗？

### ISSUE THREAD

**Issue by sle1008** [anrgct/utools-saladict#23]
今天卸载了uTools重新安装了最新版，然后再搜沙拉查词发现已经搜不到了，作者是已经下架了吗？
太可惜了啊，是因为版权问题？

**Comment by anrgct** [comment]
不是，新版本要重新适应修改后提交，我这几天改一下

**Comment by sle1008** [comment]
好的，重度用户❤ヾ(≧▽≦*)o

**Comment by anrgct** [comment]
谢谢支持~

**Comment by anrgct** [comment]
今天确认因为utools认为有版权问题，所以下架了，以后只能从github release页面手动下载安装了

**Comment by sle1008** [comment]
好的，能离线安装也行。可惜了

**Comment by Ramon403** [comment]
为啥不找原作者申请下授权呢？ 这么好的插件，不上市场，很多人根本下不了

**Comment by anrgct** [comment]
> 为啥不找原作者申请下授权呢？ 这么好的插件，不上市场，很多人根本下不了

这里的版权是指各个翻译网站的翻译内容的版权，不是沙拉查词原插件的版权，沙拉查词的作者是同意移植版本的，但是各大网站就不太可能协商了

**Comment by pessni** [comment]
> 今天确认因为utools认为有版权问题，所以下架了，以后只能从github release页面手动下载安装了

换电脑了，请问怎么下载手动安装到utools？

**Comment by pessni** [comment]
> > 今天确认因为utools认为有版权问题，所以下架了，以后只能从github release页面手动下载安装了
> 
> 换电脑了，请问怎么下载手动安装到utools？

找到了upx文件，之前没发现，几年的老用户了，非常感谢作者。
