### ISSUE TITLE
这个插件的沪江词典无效。另跪求更新最新版的沙拉查词（7.18.0）~

### ISSUE THREAD

**Issue by sle1008** [anrgct/utools-saladict#6]
一直以来原版的沙拉查词都能使用沪江词典。但是本 utools 版沙拉查词里的沪江词典无效。
另外已经三个多月过去了，希望开发者能抽出百忙时间更新插件到最新的版本。
谢谢！

**Comment by sle1008** [comment]
我身边用 utools 版的沙拉查词挺多的，贼好用。尤其是在 Linux 系统上。以前Linux 系统上好用的查词软件几乎没有，也就一个 goldendict 勉强可用。自从 utools 有了 Linux版，Linux 系统就也变相相当于拥有了一个可以全局调用的非常好用的词典。希望开发者别断更啊~~~不用更新的很频繁，但至少每隔几个版本，就同步下最新版本，谢谢！

**Comment by anrgct** [comment]
好的，我以后会定期升级一下

**Comment by sle1008** [comment]
> 好的，我以后会定期升级一下

感谢

**Comment by anrgct** [comment]
> 我身边用 utools 版的沙拉查词挺多的，贼好用。尤其是在 Linux 系统上。以前Linux 系统上好用的查词软件几乎没有，也就一个 goldendict 勉强可用。自从 utools 有了 Linux版，Linux 系统就也变相相当于拥有了一个可以全局调用的非常好用的词典。希望开发者别断更啊~~~不用更新的很频繁，但至少每隔几个版本，就同步下最新版本，谢谢！

碰到点问题，utools不能修改跨域请求的cookie，所以沪江小D词典出不来，我想想有没有办法

**Comment by sle1008** [comment]
> 碰到点问题，utools不能修改跨域请求的cookie，所以沪江小D词典出不来，我想想有没有办法

如果沪江小D不行就算了，别的词典都没啥问题。能更新下版本就ok啦

**Comment by anrgct** [comment]
> > 碰到点问题，utools不能修改跨域请求的cookie，所以沪江小D词典出不来，我想想有没有办法
> 
> 如果沪江小D不行就算了，别的词典都没啥问题。能更新下版本就ok啦

我先试试有没有别的办法

**Comment by anrgct** [comment]
沪江小D已修复，v7.18.0也更新啦

**Comment by sle1008** [comment]
> 沪江小D已修复，v7.18.0也更新啦

今天早上看论文的时候已经发现啦，太感谢！！！！
