### ISSUE TITLE
希望能自动填入沙拉查词

### ISSUE THREAD

**Issue by ttttmr** [anrgct/utools-saladict#8]
1. 快捷键打开utools，输入单词
2. 下方出现沙拉选项，回车选择沙拉
3. 进入沙拉后，需要再次输入才能查询

可以看这个gif

![rldUII.gif](https://s3.ax1x.com/2020/12/16/rldUII.gif)

期望能在utools中输入，自动填在沙拉中

**Comment by anrgct** [comment]
如果项目出现不能快捷查词或者词典设置页面错乱等问题，请到utools插件中心——账号与数据——沙拉查词——文档——清空，重启utools，打开沙拉查词即可

**Comment by ttttmr** [comment]
感谢，可以用了
